services:
  db:
    image: postgres:14
    container_name: ecom_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - custom

  app:
    build:
      context: ./app
    container_name: ecom_app
    command: sh -c "python init_db.py && python main.py"
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - custom

networks:
  custom:
    driver: bridge
